// Generated by CoffeeScript 1.6.2
/*
WebSocket Interface for the WebSocketRails client.
*/


(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  WebSocketRails.WebSocketConnection = (function(_super) {
    __extends(WebSocketConnection, _super);

    WebSocketConnection.prototype.connection_type = 'websocket';

    function WebSocketConnection(url, dispatcher) {
      var _this = this;

      this.url = url;
      this.dispatcher = dispatcher;
      WebSocketConnection.__super__.constructor.apply(this, arguments);
      if (this.url.match(/^wss?:\/\//)) {
        console.log("WARNING: Using connection urls with protocol specified is depricated");
      } else if (window.location.protocol === 'https:') {
        this.url = "wss://" + this.url;
      } else {
        // CHANGED TO ALWAYS USE SSL -- STILL WORKS EVERYWHERE  . . . 
        this.url = "wss://" + this.url;
      }
      this._conn = new WebSocket(this.url);
      this._conn.onmessage = function(event) {
        var event_data;

        event_data = JSON.parse(event.data);
        return _this.on_message(event_data);
      };
      this._conn.onclose = function(event) {
        return _this.on_close(event);
      };
      this._conn.onerror = function(event) {
        return _this.on_error(event);
      };
    }

    WebSocketConnection.prototype.close = function() {
      return this._conn.close();
    };

    WebSocketConnection.prototype.send_event = function(event) {
      WebSocketConnection.__super__.send_event.apply(this, arguments);
      return this._conn.send(event.serialize());
    };

    return WebSocketConnection;

  })(WebSocketRails.AbstractConnection);

}).call(this);
